shell: Fix some UX annoyances
tweag/npmlock2nix pull request #56
Opened 2021-03-20 13:50 UTC by adisbladis

This PR adds two minor changes:
- Removes existing node_modules symlink if it is a Nix store path #50 
- Respects explicitly passed attributes like `buildInputs`, `passthru` & `shellHook`

2021-03-22 13:46 UTC, andir commented on internal.nix
> +        # If node_modules is a managed symlink we can safely remove it and install a new one
This code should probably be moved into the `add_node_modules_to_cwd` function?

2021-03-22 13:51 UTC, andir commented
We should also add those newly accepted attributes to the README.md which states the public API available for users.

2021-03-22 13:51 UTC, gilligan requested changes
LGTM - let's just follow @andir 's suggestion of moving the `node_modules` logic go the `add_node_modules_to_cwd` function

2021-07-01 13:19 UTC, andir commented
I rebased this, added tests and fixed up some minor issues in the related areas of the code.

2021-07-13 08:25 UTC, gilligan approved these changes

2021-07-13 08:26 UTC, merged